spring:
  application:
    name: server-wx-ssm
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 80
WX:
  APPID: 
  APPSECERET: 
  TOKEN: VEvG4Fls4xAux
  LANG: zh_CN
  EXPIRESECONDS: 2592000 #二维码过期时间
  CORPID:  #企业号id
  SECRECT:  #企业号应用SECRECT
  APISECRECT:  #通讯录SECRECT
  COTOKEN: 
  EncodingAESKey: 